/*
 * IoT Edge Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018-06-28
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde_derive::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct IdentitySpec {
    #[serde(rename = "moduleId")]
    module_id: String,
    #[serde(rename = "managedBy", skip_serializing_if = "Option::is_none")]
    managed_by: Option<String>,
}

impl IdentitySpec {
    pub fn new(module_id: String) -> Self {
        IdentitySpec {
            module_id,
            managed_by: None,
        }
    }

    pub fn set_module_id(&mut self, module_id: String) {
        self.module_id = module_id;
    }

    pub fn with_module_id(mut self, module_id: String) -> Self {
        self.module_id = module_id;
        self
    }

    pub fn module_id(&self) -> &String {
        &self.module_id
    }

    pub fn set_managed_by(&mut self, managed_by: String) {
        self.managed_by = Some(managed_by);
    }

    pub fn with_managed_by(mut self, managed_by: String) -> Self {
        self.managed_by = Some(managed_by);
        self
    }

    pub fn managed_by(&self) -> Option<&str> {
        self.managed_by.as_ref().map(AsRef::as_ref)
    }

    pub fn reset_managed_by(&mut self) {
        self.managed_by = None;
    }
}
