/*
 * IoT Edge Management API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018-06-28
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde_derive::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RuntimeStatus {
    #[serde(rename = "status")]
    status: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    description: Option<String>,
}

impl RuntimeStatus {
    pub fn new(status: String) -> Self {
        RuntimeStatus {
            status,
            description: None,
        }
    }

    pub fn set_status(&mut self, status: String) {
        self.status = status;
    }

    pub fn with_status(mut self, status: String) -> Self {
        self.status = status;
        self
    }

    pub fn status(&self) -> &String {
        &self.status
    }

    pub fn set_description(&mut self, description: String) {
        self.description = Some(description);
    }

    pub fn with_description(mut self, description: String) -> Self {
        self.description = Some(description);
        self
    }

    pub fn description(&self) -> Option<&str> {
        self.description.as_ref().map(AsRef::as_ref)
    }

    pub fn reset_description(&mut self) {
        self.description = None;
    }
}
