#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        if [ -f /etc/iotedge/config.yaml ]; then
            rm /etc/iotedge/config.yaml
        fi
    ;;

    upgrade)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
