let environmentPrefix = "<ENVIRONMENT>";
let platform = "<PLATFORM>";
let memoryThreshold = todouble("<MEMORY.THRESHOLD>");
let mostRecentTestId = toscalar(sanitizedTestMetrics 
| where device contains environmentPrefix and device contains platform
| order by TimeGenerated
| take 1
| project testId);
let filtered = sanitizedTestMetrics
| where testId == mostRecentTestId;
let filteredWithMaxTime = filtered
| summarize maxTimeGenerated = max(TimeGenerated);
let maxTimeGenerated = toscalar(filteredWithMaxTime);
let alertContext = filtered
| where TimeGenerated < maxTimeGenerated and TimeGenerated > maxTimeGenerated - <ALERTING.INTERVAL>m;
alertContext
| where Name_s == "edgeAgent_used_memory_bytes"
| where moduleName == "edgeAgent"
| order by TimeGenerated
| take 1 
| where isnan(value) or value > memoryThreshold or isnull(value)