let environmentPrefix = "<ENVIRONMENT>";
let platform = "<PLATFORM>";
let memoryThreshold = todouble("<MEMORY.THRESHOLD>");
let mostRecentTestId = toscalar(sanitizedTestMetrics 
| where device contains environmentPrefix and device contains platform
| order by TimeGenerated
| take 1
| project testId);
let filtered = sanitizedTestMetrics
| where testId == mostRecentTestId;
let filteredWithMaxTime = filtered
| summarize maxTimeGenerated = max(TimeGenerated);
let maxTimeGenerated = toscalar(filteredWithMaxTime);
let alertContext = filtered
| where TimeGenerated < maxTimeGenerated and TimeGenerated > maxTimeGenerated - <ALERTING.INTERVAL>m;
let totalMemoryAvailable = toscalar(alertContext
| where Name_s == "edgeAgent_total_memory_bytes"
| order by moduleName, TimeGenerated
| where moduleName == "host"
| extend moduleName = "total_memory"
| take 1
| project value);
alertContext
| where Name_s == "edgeAgent_used_memory_bytes"
| where moduleName == "edgeHub"
| order by TimeGenerated
| take 1 
| extend value = value / totalMemoryAvailable
| where isnan(value) or value > memoryThreshold or isnull(value)