let environmentPrefix = "<ENVIRONMENT>";
let platform = "<PLATFORM>";
let memoryThresholdAmd = todouble("<MEMORY.THRESHOLD.AMD>");
let memoryThresholdArm = todouble("<MEMORY.THRESHOLD.ARM>");
let mostRecentTestId = toscalar(sanitizedTestMetrics 
| where device contains environmentPrefix and device contains platform
| order by TimeGenerated
| take 1
| project testId);
let filtered = sanitizedTestMetrics
| where testId == mostRecentTestId;
let filteredWithMaxTime = filtered
| summarize maxTimeGenerated = max(TimeGenerated);
let maxTimeGenerated = toscalar(filteredWithMaxTime);
let alertContext = filtered
| where TimeGenerated < maxTimeGenerated and TimeGenerated > maxTimeGenerated - <ALERTING.INTERVAL>m;
alertContext
| where Name_s == "edgeAgent_used_memory_bytes"
| where moduleName == "edgeAgent"
| order by TimeGenerated
| take 1 
| where isnan(value) or isnull(value) or value > memoryThresholdAmd and hostPlatform contains "amd64" or value > memoryThresholdArm and hostPlatform contains "arm"