let testId = "<TEST.ID>";
let cpuThreshold = <CPU.THRESHOLD>;
let filtered = sanitizedTestMetrics
| where testId == testId;
let filteredWithMaxTime = filtered
| summarize maxTimeGenerated = max(TimeGenerated);
let maxTimeGenerated = toscalar(filteredWithMaxTime);
let alertContext = filtered
| where TimeGenerated < maxTimeGenerated and TimeGenerated > maxTimeGenerated - <ALERTING.INTERVAL>m;
alertContext
| where Name_s == "edgeAgent_used_cpu_percent"
| where quantile == "0.9"
| where moduleName == "edgeAgent"
| order by TimeGenerated
| take 1 
| where isnan(value) or value > cpuThreshold or isnull(value)