let testId = "<TEST.ID>";
let target = <TARGET>;
let filtered = testMetrics_CL
| extend dimensions=parse_json(Tags_s)
| where tostring(dimensions.testId) == testId;
let filteredWithMaxTime = filtered
| summarize maxTimeGenerated = max(TimeGenerated);
let maxTimeGenerated = toscalar(filteredWithMaxTime);
let alertContext = filtered
| where TimeGenerated < maxTimeGenerated and TimeGenerated > maxTimeGenerated - <ALERTING.INTERVAL>m;
alertContext
| where Name_s == "<METRIC.NAME>"
<TAG.FILTER.QUERY>
| order by TimeGenerated
| take 1
| where isnan(Value_d) or Value_d <COMPARISON> target or isnull(Value_d)