.\" (C) Copyright 2018 Microsoft. All rights reserved.
.TH IOTEDGED 8 "Azure IoT Edge User Manuals" "June 2018"

.SH NAME
iotedged \- Azure IoT Edge Security Daemon
.SH SYNOPSIS
.PP
\fBiotedged\fP
[\fB\-h\fP|\fB\-\-help\fP]
[\fB\-v\fP|\fB\-\-version\fP]
[\fB\-c\fP \fIFILE\fP|\fB\-\-config\-file\fP=\fIFILE\fP]
.br
.SH DESCRIPTION
This manual page documents the \fBiotedged\fP.
.PP
The IoT Edge Security Daemon (iotedged) manages provisioning of the edge device,
creation of sas tokens and certificates for connecting to IoT Hub, and access control to any hardware security module on the device.
.PP
In order to achieve this, it must be the component that executes the modules. Module lifecycle is performed via this daemon by the Edge Agent. The daemon serves two APIs, the management API and workload API.
.PP
The management API contains operations for creating, starting, stopping, removing, etc. modules. Access to this API is restricted to the Edge Agent only.
.PP
The workload API contains operations for modules to retrieve sas tokens and certificates for use at runtime.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.TP
\fB\-c \fP\fIFILE\fP, \fB\-\-config\-file\fP=\fIFILE\fP
Sets the daemon configuration file.
.RE
.SH SEE ALSO
.BR iotedge (1),
.br
.SH HISTORY
.PP
June 2018, Initial release
