/*
 * IoT Edge Module Workload API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018-06-28
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use hyper::client::connect::Connect;
use hyper::{Client, Uri};

pub struct Configuration<C: Connect> {
    pub base_path: String,
    pub user_agent: Option<String>,
    pub client: Client<C>,
    pub uri_composer: Box<dyn Fn(&str, &str) -> anyhow::Result<Uri>>,
}

impl<C: Connect> Configuration<C> {
    pub fn new(client: Client<C>) -> Self {
        Configuration {
            base_path: "http://localhost".to_owned(),
            user_agent: Some(format!("edgelet/{}", env!("CARGO_PKG_VERSION"))),
            client,
            uri_composer: Box::new(|base_path, path| {
                format!("{}{}", base_path, path)
                    .parse()
                    .map_err(|e| anyhow::anyhow!("Url parse error: {}", e))
            }),
        }
    }
}
