#!/bin/sh
set -e

case "$1" in
    purge)
        systemctl daemon-reload

        if [ -d /etc/aziot ]; then
            if [ -d /etc/aziot/edged ]; then
                rm -rf /etc/aziot/edged
            fi

            if [ -z "$(ls -A /etc/aziot)" ]; then
                rm -rf /etc/aziot
            fi
        fi

        if [ -d /var/log/aziot ]; then
            rm -rf /var/log/aziot
        fi

        /usr/sbin/userdel iotedge

        if [ -d /var/lib/aziot ] && [ -z "$(ls -A /var/lib/aziot)" ]; then
            rm -rf /var/lib/aziot
        fi
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


#DEBHELPER#

exit 0
