#!/bin/sh
set -e

USER=iotedge
GROUP=iotedge

case "$1" in
    configure)
        if id -u $USER > /dev/null 2>&1; then
            if [ ! -d /var/lib/aziot/edged ]; then
                mkdir -p /var/lib/aziot/edged
            fi
            if [ ! -d /var/log/aziot/edged ]; then
                mkdir -p /var/log/aziot/edged
            fi
            chown ${USER}:${GROUP} /var/lib/aziot/edged
            chown ${USER}:${GROUP} /var/log/aziot/edged
            chown root:root /etc/aziot/config.toml.edge.template
            chown ${USER}:${GROUP} /etc/aziot/edged/config.toml.default
            chown ${USER}:${GROUP} /etc/aziot/edged/config.d

            chmod 755 /var/lib/aziot/edged
            chmod 755 /var/log/aziot/edged
            chmod 600 /etc/aziot/config.toml.edge.template
            chmod 400 /etc/aziot/edged/config.toml.default
            chmod 700 /etc/aziot/edged/config.d

        fi

        if [ ! -f '/etc/aziot/config.toml' ]; then
            echo "==============================================================================="
            echo ""
            echo "                              Azure IoT Edge"
            echo ""
            echo "  IMPORTANT: Please configure the device with provisioning information."
            echo ""

            if [ -f '/etc/iotedge/config.yaml' ]; then
                echo "  Detected /etc/iotedge/config.yaml from a previously installed version"
                echo "  of IoT Edge. You can import its configuration using:"
                echo ""
                echo "    iotedge config import"
                echo ""
                echo "  To create a new configuration from scratch instead, copy the template file "
            else
                echo "  To create a new configuration, copy the template file "
            fi

            echo "  at /etc/aziot/config.toml.edge.template to /etc/aziot/config.toml,"
            echo "  update it with your device information, then apply your configuration changes"
            echo "  with:"
            echo ""
            echo "    iotedge config apply"
            echo ""
            echo "  You may need to run iotedge config commands with sudo, depending on "
            echo "  your environment."
            echo ""
            echo "==============================================================================="
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


#DEBHELPER#

exit 0
