/*
 * IotHub Gateway Service APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Service
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
use failure::Error;
use failure::err_msg;
use hyper::client::Connect;
use hyper::{Client, Uri};
use hyper::error::UriError;

pub struct Configuration<C: Connect> {
    pub base_path: String,
    pub user_agent: Option<String>,
    pub client: Client<C>,
    pub uri_composer: Box<Fn(&str, &str) -> Result<Uri, Error>>,
}

impl<C: Connect> Configuration<C> {
    pub fn new(client: Client<C>) -> Configuration<C> {
        Configuration {
            base_path: "https://fully-qualified-iothubname.azure-devices.net".to_owned(),
            user_agent: Some("edgelet/0.1.0".to_owned()),
            client: client,
            uri_composer: Box::new(|base_path, path| {
                format!("{}{}", base_path, path)
                    .parse()
                    .map_err(|_| format_err!("Url parse error"))
            }),
        }
    }
}
