/*
 * IoT Edge Hosting Environment API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-04-10
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde_derive::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DeviceConnectionInfo {
    /// The host name of the IoT hub.
    #[serde(rename = "hubName")]
    hub_name: String,
    /// The ID of the device in IoT hub.
    #[serde(rename = "deviceId")]
    device_id: String,
}

impl DeviceConnectionInfo {
    pub fn new(hub_name: String, device_id: String) -> DeviceConnectionInfo {
        DeviceConnectionInfo {
            hub_name,
            device_id,
        }
    }

    pub fn set_hub_name(&mut self, hub_name: String) {
        self.hub_name = hub_name;
    }

    pub fn with_hub_name(mut self, hub_name: String) -> DeviceConnectionInfo {
        self.hub_name = hub_name;
        self
    }

    pub fn hub_name(&self) -> &String {
        &self.hub_name
    }

    pub fn set_device_id(&mut self, device_id: String) {
        self.device_id = device_id;
    }

    pub fn with_device_id(mut self, device_id: String) -> DeviceConnectionInfo {
        self.device_id = device_id;
        self
    }

    pub fn device_id(&self) -> &String {
        &self.device_id
    }
}
