.\" (C) Copyright 2018 Microsoft. All rights reserved.
.TH IOTEDGE 1 "Azure IoT Edge User Manuals" "June 2018"

.SH NAME
iotedge \- Management tool for Azure IoT Edge
.SH SYNOPSIS
.PP
\fBiotedge\fP
[\fB\-H\fP \fIHOST\fP|\fB\-\-host\fP-\fIHOST\fP]
.RI [ subcommands ]
.br
.SH DESCRIPTION
This manual page documents the
\fBiotedge\fP tool.
.PP
\fBiotedge\fP is a tool to retrieve status and manage the IoT Edge runtime.
It communicates directly with the IoT Edge daemon's management socket.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B \-H <HOST>, \-\-host <HOST>
Set the location of the daemon's management socket.
.SH COMMANDS
.PP
Use "iotedge help" or "iotedge --help" to get an overview of available commands.
.RE
.SH SEE ALSO
.BR iotedged (8),
.br
.SH HISTORY
.PP
June 2018, Initial release
