{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "BranchName",
    "label": "Branch Name",
    "query": "SELECT SourceBranch from VstsBuild GROUP BY SourceBranch"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 }, "content": "# Builds\n\n\n" },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 }, "content": "# CI\n\n\n" },
  { "type": "text", "gridPos": { "h": 2, "w": 10, "x": 13, "y": 0 }, "content": "# E2E\n\n\n" },
  {
   "title": "Build Images",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50))\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result \nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'PartiallySucceeded', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\n\nSELECT Result\nFROM\n@BuildStatus\nWHERE SourceBranch = '$BranchName' AND (DefinitionName = 'Build Images')"
    }
   ]
  },
  {
   "title": "Build Edgelet",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50))\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result \nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'PartiallySucceeded', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\n\nSELECT Result\nFROM\n@BuildStatus\nWHERE SourceBranch = '$BranchName' AND (DefinitionName = 'Edgelet Packages')"
    }
   ]
  },
  {
   "title": "CI",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50))\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result \nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'PartiallySucceeded', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\nSELECT Result\nFROM\n@BuildStatus\nWHERE SourceBranch = '$BranchName' AND DefinitionName = 'CI'"
    }
   ]
  },
  {
   "title": "Edgelet CI",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50))\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result \nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'PartiallySucceeded', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\nSELECT Result\nFROM\n@BuildStatus\nWHERE SourceBranch = '$BranchName' AND DefinitionName = 'Edgelet CI'"
    }
   ]
  },
  {
   "title": "Libiothsm CI",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50))\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result \nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\nSELECT Result\nFROM\n@BuildStatus\nWHERE SourceBranch = '$BranchName' AND DefinitionName = 'Libiothsm CI'"
    }
   ]
  },
  {
   "title": "Longhaul",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50), QueueTime DATETIME)\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result, QueueTime\nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\nSELECT TOP 1 RESULT FROM @BuildStatus\nWHERE SourceBranch = '$BranchName' AND DefinitionName = 'Longhaul Test Release'\nORDER BY QueueTime DESC"
    }
   ]
  },
  {
   "title": "Nested Longhaul",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50), QueueTime DATETIME)\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result, QueueTime\nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\nSELECT TOP 1 RESULT FROM @BuildStatus\nWHERE SourceBranch = '$BranchName' AND DefinitionName = 'Nested Longhaul Test'\nORDER BY QueueTime DESC"
    }
   ]
  },
  {
   "title": "E2E",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 6 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50))\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result \nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'PartiallySucceeded', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\nSELECT Result\nFROM\n@BuildStatus\nWHERE SourceBranch = '$BranchName' AND (DefinitionName = 'New E2E Test')"
    }
   ]
  },
  {
   "title": "Nested E2E",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 6 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50))\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result \nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'PartiallySucceeded', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\nSELECT Result\nFROM\n@BuildStatus\nWHERE SourceBranch = '$BranchName' AND (DefinitionName = 'Nested E2E Test')"
    }
   ]
  },
  {
   "title": "Connectivity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 10 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50))\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result \nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\nSELECT Result\nFROM\n@BuildStatus\nWHERE SourceBranch = '$BranchName' AND (DefinitionName = 'Connectivity Test')"
    }
   ]
  },
  {
   "title": "Nested Connectivity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 10 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50))\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result \nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\nSELECT Result\nFROM\n@BuildStatus\nWHERE SourceBranch = '$BranchName' AND (DefinitionName = 'Nested Connectivity Test')"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "content": "-----------------------\n# Bugs\n\n\n"
  },
  {
   "title": "In-Progress Bugs | Priority One",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT SUM(BugCount) FROM VstsBug\nWHERE Priority = '1' AND InProgress = 'true';"
    }
   ]
  },
  {
   "title": "Total Bugs | Priority One",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 17 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT SUM(BugCount) FROM VstsBug\nWHERE Priority = '1';"
    }
   ]
  },
  {
   "title": "In-Progress Bugs | Priority Two",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT SUM(BugCount) FROM VstsBug\nWHERE Priority = '2' AND InProgress = 'true';"
    }
   ]
  },
  {
   "title": "Total Bugs | Priority Two",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT SUM(BugCount) FROM VstsBug\nWHERE Priority = '2';"
    }
   ]
  },
  {
   "title": "In-Progress Bugs | Priority Other",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 17 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT SUM(BugCount) FROM VstsBug\nWHERE Priority = 'Other' AND InProgress = 'true';"
    }
   ]
  },
  {
   "title": "Total Bugs | Priority Other",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 17 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT SUM(BugCount) FROM VstsBug\nWHERE Priority = 'Other';"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "DECLARE @BugInfo TABLE (AreaPath VARCHAR(200), Priority VARCHAR(200), InProgress VARCHAR(200), BugCount Int)\n\nINSERT INTO @BugInfo\nSELECT AreaPath, Priority, Tmp = CASE InProgress WHEN 1 THEN 'Started' WHEN 0 THEN 'NotStarted' END, BugCount FROM VstsBug;\n\nDECLARE @BugDescCounts TABLE (AreaPath VARCHAR(200), Description VARCHAR(200), BugCount Int)\n\nINSERT INTO @BugDescCounts\nSELECT AreaPath, Description = CONCAT('(Priority: ', Priority, ') (Status: ', InProgress, ')' ), BugCount FROM @BugInfo\n\nSELECT * FROM @BugDescCounts\nPIVOT (\n    MAX(BugCount)\n    FOR Description IN (\n      [(Priority: 1) (Status: Started)],\n      [(Priority: 1) (Status: NotStarted)],\n      [(Priority: 2) (Status: Started)],\n      [(Priority: 2) (Status: NotStarted)],\n      [(Priority: Other) (Status: Started)],\n      [(Priority: Other) (Status: NotStarted)]\n    )) AS Description2\nORDER BY AreaPath ASC\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "content": "------------------ \n# Connectivity"
  },
  {
   "title": "Test Scenarios",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "let mostRecentTestBuildId = toscalar(connectivity_CL\n| where TestInfo_ImagesSourceBranch_s == \"$BranchName\"\n| where TestInfo_TestName_s == \"connectivity (single-node)\"\n| summarize arg_max(TestInfo_TestBuildId_s, TimeGenerated)\n| project TestInfo_TestBuildId_s);\nconnectivity_CL\n| where TestInfo_TestBuildId_s == mostRecentTestBuildId\n| extend Scenario = strcat(TestInfo_NetworkDescription_s, \" | \", TestInfo_HostPlatform_s)\n| mv-expand todynamic(TestResultReports_s)\n| extend TestName = TestResultReports_s.TestDescription\n| extend IsTestPassed = iff(TestResultReports_s.IsPassed == \"true\", 1, 0)\n| project TestName, Scenario, IsTestPassed\n| evaluate pivot(Scenario, avg(IsTestPassed))\n| where TestName != \"\"",
      "resultFormat": "table",
      "workspace": "fdf47b96-87f3-4b86-90b9-d83e2deae8a0"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "5ed2dcb6-29bb-40de-a855-8c24a8260343"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 50 },
   "content": "------------------ \n# Nested Connectivity"
  },
  {
   "title": "Test Scenarios",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "let mostRecentTestBuildId = toscalar(connectivity_CL\n| where TestInfo_ImagesSourceBranch_s == \"$BranchName\"\n| where TestInfo_TestName_s == \"connectivity (nested-broker)\"\n| summarize arg_max(TestInfo_TestBuildId_s, TimeGenerated)\n| project TestInfo_TestBuildId_s);\nconnectivity_CL\n| where TestInfo_TestBuildId_s == mostRecentTestBuildId\n| extend Scenario = strcat(TestInfo_NetworkDescription_s, \" | \", TestInfo_HostPlatform_s)\n| mv-expand todynamic(TestResultReports_s)\n| extend TestName = TestResultReports_s.TestDescription\n| extend IsTestPassed = iff(TestResultReports_s.IsPassed == \"true\", 1, 0)\n| project TestName, Scenario, IsTestPassed\n| evaluate pivot(Scenario, avg(IsTestPassed))\n| where TestName != \"\"",
      "resultFormat": "table",
      "workspace": "fdf47b96-87f3-4b86-90b9-d83e2deae8a0"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "5ed2dcb6-29bb-40de-a855-8c24a8260343"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 69 },
   "content": "------------------ \n# Longhaul"
  },
  {
   "title": "Test Scenarios",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "let branchIdentifier = case(\"$BranchName\" == \"refs/heads/master\", \"master\", \"$BranchName\" == \"refs/heads/release/1.0.8\", \"1.0.8\", \"$BranchName\" == \"refs/heads/release/1.0.9\", \"1.0.9\", \"$BranchName\" == \"refs/heads/release/1.0.10\", \"1.0.10\", \"$BranchName\" == \"refs/heads/release/1.1\", \"1.1\", \"$BranchName\" == \"refs/heads/release/1.2\", \"1.2\", \"None\");\nlet mostRecentBuildId = toscalar(longhaul_CL\n\r| where TestInfo_BuildSourceBranch_s == branchIdentifier\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\r\n\r\n\r\n\r\n| where TestInfo_TestName_s == \"longhaul (single-node)\"\n| summarize arg_max(TimeGenerated, TestInfo_TestBuildId_s)\n\r\n\r\r\n\r\r\r\r\n| project TestInfo_TestBuildId_s);\r\nlonghaul_CL\n\r\n| where TestInfo_TestBuildId_s == mostRecentBuildId\r\n| summarize arg_max(TimeGenerated, *) by TestInfo_HostPlatform_s\r\n| mv-expand todynamic(TestResultReports_s)\r\n| extend TestDescription = TestResultReports_s.TestDescription\r\n| extend Result = TestResultReports_s.IsPassed\r\n| extend Result = iff(TestResultReports_s.IsPassed == \"true\", 1, 0)\r\n| extend HostPlatform = TestInfo_HostPlatform_s\r\n| project HostPlatform, TestDescription, Result\r\n| evaluate pivot(HostPlatform, avg(Result))",
      "resultFormat": "table",
      "workspace": "fdf47b96-87f3-4b86-90b9-d83e2deae8a0"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "5ed2dcb6-29bb-40de-a855-8c24a8260343"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 87 },
   "content": "------------------ \n# Nested Longhaul"
  },
  {
   "title": "Test Scenarios",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "let branchIdentifier = case(\"$BranchName\" == \"refs/heads/master\", \"master\", \"$BranchName\" == \"refs/heads/release/1.0.8\", \"1.0.8\", \"$BranchName\" == \"refs/heads/release/1.0.9\", \"1.0.9\", \"$BranchName\" == \"refs/heads/release/1.0.10\", \"1.0.10\", \"$BranchName\" == \"refs/heads/release/1.1\", \"1.1\", \"$BranchName\" == \"refs/heads/release/1.2\", \"1.2\", \"None\");\nlet mostRecentBuildId = toscalar(longhaul_CL\n\r| where TestInfo_BuildSourceBranch_s == branchIdentifier\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\r\n\r\n\r\n\r\n| where TestInfo_TestName_s == \"longhaul (nested-broker)\" or TestInfo_TestName_s == \"longhaul (nested-non-broker)\"\n| summarize arg_max(TestInfo_TestBuildId_s, TimeGenerated)\n| project TestInfo_TestBuildId_s);\n\r\nlonghaul_CL\n| where TestInfo_TestBuildId_s == mostRecentBuildId\n| summarize arg_max(TimeGenerated, *) by TestInfo_HostPlatform_s, TestInfo_TestName_s\n| mv-expand todynamic(TestResultReports_s)\n| extend TestDescription = TestResultReports_s.TestDescription\n| extend Result = TestResultReports_s.IsPassed\n| extend Result = iff(TestResultReports_s.IsPassed == \"true\", 1, 0)\n| extend HostPlatform = TestInfo_HostPlatform_s\n| extend TestName = TestInfo_TestName_s\n| extend TestContext = strcat(HostPlatform, \" | \", TestName)\n| project TestDescription, TestContext, Result\n| evaluate pivot(TestContext, avg(Result))",
      "resultFormat": "table",
      "workspace": "fdf47b96-87f3-4b86-90b9-d83e2deae8a0"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "5ed2dcb6-29bb-40de-a855-8c24a8260343"
    }
   ]
  }
 ]
}