{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "BranchName",
    "label": "Branch Name",
    "query": "SELECT SourceBranch from VstsBuild GROUP BY SourceBranch"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 }, "content": "# Build\n\n\n" },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 }, "content": "# CI\n\n\n" },
  { "type": "text", "gridPos": { "h": 2, "w": 10, "x": 13, "y": 0 }, "content": "# E2E\n\n\n" },
  {
   "title": "Build Images",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50))\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result \nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\n\nSELECT Result\nFROM\n@BuildStatus\nWHERE SourceBranch = '$BranchName' AND (DefinitionName = 'Build Images')"
    }
   ]
  },
  {
   "title": "Build Edgelet",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50))\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result \nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\n\nSELECT Result\nFROM\n@BuildStatus\nWHERE SourceBranch = '$BranchName' AND (DefinitionName = 'Edgelet Packages')"
    }
   ]
  },
  {
   "title": "CI",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50))\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result \nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\nSELECT Result\nFROM\n@BuildStatus\nWHERE SourceBranch = '$BranchName' AND DefinitionName = 'CI'"
    }
   ]
  },
  {
   "title": "Edgelet CI",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50))\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result \nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\nSELECT Result\nFROM\n@BuildStatus\nWHERE SourceBranch = '$BranchName' AND DefinitionName = 'Edgelet CI'"
    }
   ]
  },
  {
   "title": "Libiothsm CI",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50))\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result \nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\nSELECT Result\nFROM\n@BuildStatus\nWHERE SourceBranch = '$BranchName' AND DefinitionName = 'Libiothsm CI'"
    }
   ]
  },
  {
   "title": "Old E2E",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @ReleaseEnvironmentStatus TABLE (ReleaseId VARCHAR(50), Result VARCHAR(50))\n\nINSERT INTO @ReleaseEnvironmentStatus\nSELECT ReleaseId, Status FROM VstsReleaseEnvironment\n\nUPDATE @ReleaseEnvironmentStatus SET Result = REPLACE(Result, 'Failed', '0')\nUPDATE @ReleaseEnvironmentStatus SET Result = REPLACE(Result, 'Rejected', '0')\nUPDATE @ReleaseEnvironmentStatus SET Result = REPLACE(Result, 'PartiallySucceeded', '0')\nUPDATE @ReleaseEnvironmentStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @ReleaseEnvironmentStatus SET Result = REPLACE(Result, 'NotStarted', '0.5')\nUPDATE @ReleaseEnvironmentStatus SET Result = REPLACE(Result, 'InProgress', '0.5')\nUPDATE @ReleaseEnvironmentStatus SET Result = REPLACE(Result, 'Succeeded', '1')\n\nSELECT ReleaseIdToAggregatedStatus.Result AS [Old E2E] FROM \n  VstsRelease\n  INNER JOIN (SELECT ReleaseId, MIN(Result) AS Result FROM @ReleaseEnvironmentStatus GROUP BY ReleaseId) AS ReleaseIdToAggregatedStatus ON VstsRelease.Id = ReleaseIdToAggregatedStatus.ReleaseId\n    INNER JOIN (SELECT VstsRelease.DefinitionName, SourceBranch, MAX(Id) AS MaxReleaseId FROM VstsRelease GROUP BY VstsRelease.DefinitionName, SourceBranch) AS MostRecentReleasesPerDefinitionAndBranch\n      ON VstsRelease.DefinitionName = MostRecentReleasesPerDefinitionAndBranch.DefinitionName AND VstsRelease.SourceBranch = MostRecentReleasesPerDefinitionAndBranch.SourceBranch AND VstsRelease.Id = MostRecentReleasesPerDefinitionAndBranch.MaxReleaseId\n      WHERE VstsRelease.SourceBranch = '$BranchName'"
    }
   ]
  },
  {
   "title": "New E2E",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50))\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result \nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\nSELECT Result\nFROM\n@BuildStatus\nWHERE SourceBranch = '$BranchName' AND (DefinitionName = 'New E2E Test')"
    }
   ]
  },
  {
   "title": "Connectivity Test",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50))\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result \nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\nSELECT Result\nFROM\n@BuildStatus\nWHERE SourceBranch = '$BranchName' AND (DefinitionName = 'Connectivity Test')"
    }
   ]
  },
  {
   "title": "Stress Deployment",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @Environment VARCHAR(50)\nIF ('$BranchName' = 'refs/heads/master') BEGIN\n    SET @Environment = 'Stress Test'\nEND\nELSE IF ('$BranchName' = 'refs/heads/release/1.0.9') BEGIN\n    SET @Environment = 'Stress Test Release Candidate'\nEND\nELSE BEGIN\n    SET @Environment = 'Stress Test Release'\nEND\n\nDECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50), QueueTime DATETIME)\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result, QueueTime\nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\n---We will eventually only care about the desired environment instead of the most recent across all environments\n-- SELECT Result FROM @BuildStatus\n-- WHERE DefinitionName = @Environment AND SourceBranch = '$BranchName'\n-- ORDER BY QueueTime ASC\n\nSELECT TOP 1 RESULT FROM @BuildStatus\nWHERE SourceBranch = '$BranchName' AND DefinitionName LIKE '%Stress%'\nORDER BY QueueTime ASC\n"
    }
   ]
  },
  {
   "title": "Longhaul Deployment",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "DECLARE @Environment VARCHAR(50)\nIF ('$BranchName' = 'refs/heads/master') BEGIN\n    SET @Environment = 'Longhaul Test'\nEND\nELSE IF ('$BranchName' = 'refs/heads/release/1.0.9') BEGIN\n    SET @Environment = 'Longhaul Test Release Candidate'\nEND\nELSE BEGIN\n    SET @Environment = 'Longhaul Test Release'\nEND\n\nDECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50), QueueTime DATETIME)\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result, QueueTime\nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\n-- SELECT TOP 1 Result FROM @BuildStatus\n-- WHERE DefinitionName = @Environment\n-- ORDER BY QueueTime ASC\n\nSELECT TOP 1 RESULT FROM @BuildStatus\nWHERE SourceBranch = '$BranchName' AND DefinitionName LIKE '%Longhaul%'\nORDER BY QueueTime ASC"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "content": "-----------------------\n# Bugs\n\n\n"
  },
  {
   "title": "In-Progress Bugs | Priority One",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT SUM(BugCount) FROM VstsBug\nWHERE Priority = '1' AND InProgress = 'true';"
    }
   ]
  },
  {
   "title": "Total Bugs | Priority One",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT SUM(BugCount) FROM VstsBug\nWHERE Priority = '1';"
    }
   ]
  },
  {
   "title": "In-Progress Bugs | Priority Two",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT SUM(BugCount) FROM VstsBug\nWHERE Priority = '2' AND InProgress = 'true';"
    }
   ]
  },
  {
   "title": "Total Bugs | Priority Two",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT SUM(BugCount) FROM VstsBug\nWHERE Priority = '2';"
    }
   ]
  },
  {
   "title": "In-Progress Bugs | Priority Other",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT SUM(BugCount) FROM VstsBug\nWHERE Priority = 'Other' AND InProgress = 'true';"
    }
   ]
  },
  {
   "title": "Total Bugs | Priority Other",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT SUM(BugCount) FROM VstsBug\nWHERE Priority = 'Other';"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "DECLARE @BugInfo TABLE (AreaPath VARCHAR(200), Priority VARCHAR(200), InProgress VARCHAR(200), BugCount Int)\n\nINSERT INTO @BugInfo\nSELECT AreaPath, Priority, Tmp = CASE InProgress WHEN 1 THEN 'Started' WHEN 0 THEN 'NotStarted' END, BugCount FROM VstsBug;\n\nDECLARE @BugDescCounts TABLE (AreaPath VARCHAR(200), Description VARCHAR(200), BugCount Int)\n\nINSERT INTO @BugDescCounts\nSELECT AreaPath, Description = CONCAT('(Priority: ', Priority, ') (Status: ', InProgress, ')' ), BugCount FROM @BugInfo\n\nSELECT * FROM @BugDescCounts\nPIVOT (\n    MAX(BugCount)\n    FOR Description IN (\n      [(Priority: 1) (Status: Started)],\n      [(Priority: 1) (Status: NotStarted)],\n      [(Priority: 2) (Status: Started)],\n      [(Priority: 2) (Status: NotStarted)],\n      [(Priority: Other) (Status: Started)],\n      [(Priority: Other) (Status: NotStarted)]\n    )) AS Description2\nORDER BY AreaPath ASC\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 23 },
   "content": "-----------------------\n# End to End Tests\n\n\n"
  },
  {
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "WITH Release_CTE\nAS\n(\n    SELECT r.id releaseId, r.SourceBranch, e.Id envId, e.DefinitionName, e.Status, d.Id deploymentId, d.Attempt \n    FROM VstsRelease r\n    INNER JOIN VstsReleaseEnvironment e\n    ON r.Id = e.ReleaseId\n    INNER JOIN VstsReleaseDeployment d\n    ON e.Id = d.ReleaseEnvironmentId\n)\n, Most_Recent_Release\nAS\n(\n    SELECT MAX(releaseId) AS mostRecentCompletedReleaseId FROM\n    (\n        SELECT releaseId FROM Release_CTE WHERE SourceBranch = '$BranchName' AND Status != 'InProgress'\n        EXCEPT\n        SELECT releaseId FROM Release_CTE WHERE SourceBranch = '$BranchName' AND Status = 'InProgress'\n    ) CompletedReleases\n)\nSELECT * FROM\n(\n    SELECT DefinitionName, t.Name taskName, taskStatus = CASE t.Status WHEN 'succeeded' THEN 1 WHEN 'partiallySucceeded' THEN 0 WHEN 'failed' THEN 0 END\n    FROM Release_CTE x\n    INNER JOIN\n    (\n        SELECT releaseId, envId, MAX(Attempt) Attempt \n        FROM Release_CTE \n        WHERE releaseId IN (SELECT mostRecentCompletedReleaseId FROM Most_Recent_Release)\n        GROUP BY releaseId, envId\n    ) LatestDeployment\n    ON x.releaseId = LatestDeployment.releaseId\n    AND x.envId = LatestDeployment.envId\n    AND x.Attempt = LatestDeployment.Attempt\n    INNER JOIN VstsReleaseTask t\n    ON x.deploymentId = t.ReleaseDeploymentId\n    WHERE x.releaseId IN (SELECT mostRecentCompletedReleaseId FROM Most_Recent_Release)\n) t1\nPIVOT (\n    AVG(taskStatus) \n    FOR DefinitionName IN (\n        [Linux AMD64 Docker],\n        [Linux AMD64 Moby],\n        [RBPi ARM32 Moby],\n        [RBPi ARM64 Docker],\n        [VM Proxy],\n        [WinPro-x64],\n        [WinSvr-x64],\n        [WinIoT-x64]\n    )) AS pivot_t"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 44 },
   "content": "------------------ \n# Connectivity"
  },
  {
   "title": "Test Scenarios",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "let mostRecentTestBuildNumber = toscalar(connectivity_CL\n| where TestInfo_ImagesSourceBranch_s == \"$BranchName\"\n| summarize arg_max(TestInfo_TestBuildNumber_s, TimeGenerated)\n| project TestInfo_TestBuildNumber_s);\n\nconnectivity_CL\n| where TestInfo_TestBuildNumber_s == mostRecentTestBuildNumber and TestInfo_TestBuildNumber_s != \"\"\n| extend Scenario = strcat(TestInfo_NetworkDescription_s, \" | \", TestInfo_HostPlatform_s)\n| mv-expand todynamic(TestResultReports_s)\n| extend TestName = TestResultReports_s.TestDescription\n| extend IsTestPassed = iff(TestResultReports_s.IsPassed == \"true\", 1, 0)\n| project TestName, Scenario, IsTestPassed\n| evaluate pivot(Scenario, avg(IsTestPassed))\n| where TestName != \"\"",
      "resultFormat": "table",
      "workspace": "fdf47b96-87f3-4b86-90b9-d83e2deae8a0"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "5ed2dcb6-29bb-40de-a855-8c24a8260343"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 68 },
   "content": "------------------ \n# Longhaul"
  },
  {
   "title": "Test Scenarios",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "let branchIdentifier = case(\"$BranchName\" == \"refs/heads/master\", \"master\", \"$BranchName\" == \"refs/heads/release/1.0.8\", \"1.0.8\", \"$BranchName\" == \"refs/heads/release/1.0.9\", \"1.0.9\", \"None\");\nlet longhaulIdentifier = \"LongHaul\";\nlet mostRecentBuildNumber = toscalar(messagingReportsLonghaulStress_CL\n| where testInfo_TestName_s == longhaulIdentifier and branchIdentifier == testInfo_BuildSourceBranch_s\n| summarize arg_max(TimeGenerated, testInfo_TestBuildNumber_s)\n| project testInfo_TestBuildNumber_s);\nlet directMethodReport = directMethodReportsLonghaulStress_CL\n| where testInfo_TestBuildNumber_s == mostRecentBuildNumber and testInfo_TestName_s == longhaulIdentifier\n| extend Result = replace(\"True\", \"1\", tostring(isPassed_b))\n| extend Result = replace(\"False\", \"0\", tostring(Result)) \n| summarize arg_max(TimeGenerated, *) by testInfo_HostPlatform_s, moduleId_s\n| where testInfo_HostPlatform_s != \"\"\n| extend testInfo_HostPlatform_s = strcat(testInfo_HostPlatform_s, \" | \", testInfo_TestBuildNumber_s)\n| project testInfo_HostPlatform_s, moduleId_s, Result\n| extend moduleId_s = replace(\"DirectMethodSender.send\", \"DirectMethodSender\", moduleId_s)\n| extend moduleId_s = replace(\"DirectMethodSender2.send\", \"DirectMethodSender2\", moduleId_s)\n| extend moduleId_s = replace(\"DirectMethodReceiver\", \"DirectMethodSender\", moduleId_s)\n| extend moduleId_s = replace(\"DirectMethodReceiver2\", \"DirectMethodSender2\", moduleId_s) \n| evaluate pivot(moduleId_s, max(Result)); // have to use aggreation function max, but there will only ever be a max of 1 record\nlet twinsReport = twinReportsLonghaulStress_CL\n| where testInfo_TestBuildNumber_s == mostRecentBuildNumber and testInfo_TestName_s == longhaulIdentifier\n| extend Result = replace(\"True\", \"1\", tostring(isPassed_b))\n| extend Result = replace(\"False\", \"0\", tostring(Result)) \n| summarize arg_max(TimeGenerated, *) by testInfo_HostPlatform_s, moduleId_s\n| where testInfo_HostPlatform_s != \"\"\n| extend testInfo_HostPlatform_s = strcat(testInfo_HostPlatform_s, \" | \", testInfo_TestBuildNumber_s)\n| project testInfo_HostPlatform_s, moduleId_s, Result\n| evaluate pivot(moduleId_s, max(Result)); // have to use aggreation function max, but there will only ever be a max of 1 record \nlet messagingReport = messagingReportsLonghaulStress_CL\n| where testInfo_TestBuildNumber_s == mostRecentBuildNumber and testInfo_TestName_s == longhaulIdentifier\n| extend Result = replace(\"True\", \"1\", tostring(isPassed_b))\n| extend Result = replace(\"False\", \"0\", tostring(Result)) \n| summarize arg_max(TimeGenerated, *) by testInfo_HostPlatform_s, moduleId_s\n| where testInfo_HostPlatform_s != \"\"\n| extend testInfo_HostPlatform_s = strcat(testInfo_HostPlatform_s, \" | \", testInfo_TestBuildNumber_s)\n| project testInfo_HostPlatform_s, moduleId_s, Result\n| evaluate pivot(moduleId_s, max(Result)); // have to use aggreation function max, but there will only ever be a max of 1 record\ndirectMethodReport\n| join kind= leftouter (\n   twinsReport \n) on testInfo_HostPlatform_s\n| project-away testInfo_HostPlatform_s1\n| join kind= leftouter (\n   messagingReport \n) on testInfo_HostPlatform_s\n| project-away testInfo_HostPlatform_s1\n| extend loadGen1 = columnifexists(\"loadGen1\", \"0\")\n| extend loadGen2 = columnifexists(\"loadGen2\", \"0\")\n| extend tempFilter = columnifexists(\"tempFilter\", \"0\")\n| extend tempFilter2 = columnifexists(\"tempFilter2\", \"0\") \n| extend DirectMethodSender = columnifexists(\"DirectMethodSender\", \"0\")\n| extend DirectMethodSender2 = columnifexists(\"DirectMethodSender2\", \"0\")\n| extend twinTester1 = columnifexists(\"twinTester1\", \"0\")\n| extend twinTester2 = columnifexists(\"twinTester2\", \"0\")\n| project-reorder testInfo_HostPlatform_s, loadGen1, loadGen2, tempFilter, tempFilter2, DirectMethodSender, DirectMethodSender2, twinTester1, twinTester2",
      "resultFormat": "table",
      "workspace": "fdf47b96-87f3-4b86-90b9-d83e2deae8a0"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "5ed2dcb6-29bb-40de-a855-8c24a8260343"
    }
   ]
  },
  {
   "title": "KPI Violations",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "\nlet mostRecentTestBuildNumber = toscalar(sanitizedTestMetrics\n| where testType == 'LongHaul' and imagesBranchName == \"$BranchName\"\n| summarize arg_max(TimeGenerated, testBuildNumber)\n| project testBuildNumber);\nlet filtered = sanitizedTestMetrics\n| where testBuildNumber == mostRecentTestBuildNumber and testType == \"LongHaul\";\nlet filteredWithMinTime = filtered\n| summarize minTimeGenerated = min(TimeGenerated);\nlet filteredWithMaxTime = filtered\n| summarize maxTimeGenerated = max(TimeGenerated);\nlet minTimeGenerated = toscalar(filteredWithMinTime);\nlet maxTimeGenerated = toscalar(filteredWithMaxTime);\nlet environmentPrefix = toscalar(filtered\n| where device contains \"Linux\"\n| extend device = substring(device, 0, 3)\n| project device);\nlet alerts = Alert\n| where TimeGenerated > minTimeGenerated + 15m and TimeGenerated < maxTimeGenerated and AlertName contains environmentPrefix\n| extend device = extract(\".*longhaul\", 0, AlertName)\n| order by TimeGenerated;\nlet descriptions = datatable(description: string)\n[\"Reported Metrics\",\n \"Queue Length\",\n \"Upstream Message Rate\",\n \"Local Message Rate\",\n \"Reported Property Rate\",\n \"Queue Length\",\n \"Edge Agent CPU\",\n \"Edge Hub CPU\",\n \"Edge Agent Memory\",\n \"Edge Hub Memory\",\n \"Failed Module Starts\",\n \"Disk Space\"\n ];\n let getConsecutiveFailures = (T1:(AlertName: string, TimeGenerated: datetime)) {\n    T1\n    | order by AlertName, TimeGenerated asc\n    | extend nextAlertName = next(AlertName, 1)\n    | extend nextTime = next(TimeGenerated, 1)\n    | extend next2Time = next(TimeGenerated, 2)\n    | project-reorder AlertName, TimeGenerated\n    | extend isError = iff(nextTime - TimeGenerated < 20m and next2Time - nextTime < 20m and AlertName == nextAlertName, 1, 0)\n    | where isError == 1\n};\nlet devices = filtered\n| summarize count() by device\n| extend device = tolower(device)\n| project device;\nlet deviceDescriptions = devices \n| extend dummy=1 | join kind = inner (descriptions | extend dummy=1) on dummy // dummy cross join from AzureDiagnostics\n| project device, description\n| extend violations = 0; \nlet numberOfMetrics = alerts\n| where AlertDescription contains \"number-of-metrics-too-low\" or AlertDescription contains \"number-of-metrics-too-high\"\n| summarize violations = count() by device\n| extend description = \"Reported Metrics\";\nlet upstreamMessageRate = getConsecutiveFailures(alerts)\n| where AlertDescription contains \"upstream-message-rate\" or AlertDescription contains \"no-upstream-messages\"\n| summarize violations = count() by device\n| extend description = \"Upstream Message Rate\";\nlet localMessageRate = alerts\n| where AlertDescription contains \"local-message-rate\" or AlertDescription contains \"no-local-messages\"\n| summarize violations = count() by device\n| extend description = \"Local Message Rate\";\nlet reportedPropertyRate = getConsecutiveFailures(alerts)\n| where AlertDescription contains \"reported-property-rate\" or AlertDescription contains \"no-reported-properties\"\n| summarize violations = count() by device\n| extend description = \"Reported Property Rate\";\nlet queueLength = getConsecutiveFailures(alerts)\n| where AlertDescription contains \"queue-length\"\n| summarize violations = count() by device\n| extend description = \"Queue Length\";\nlet edgeAgentCPU = getConsecutiveFailures(alerts)\n| where AlertDescription contains \"edge-agent-cpu\"\n| summarize violations = count() by device\n| extend description = \"Edge Agent CPU\";\nlet edgeHubCPU = getConsecutiveFailures(alerts)\n| where AlertDescription contains \"edge-hub-cpu\"\n| summarize violations = count() by device\n| extend description = \"Edge Hub CPU\";\nlet edgeAgentMemory = getConsecutiveFailures(alerts)\n| where AlertDescription contains \"edge-agent-memory\"\n| summarize violations = count() by device\n| extend description = \"Edge Agent Memory\";\nlet edgeHubMemory = getConsecutiveFailures(alerts)\n| where AlertDescription contains \"edge-hub-memory\"\n| summarize violations = count() by device\n| extend description = \"Edge Hub Memory\";\nlet moduleStarts = alerts\n| where AlertDescription contains \"failed-module-starts\"\n| summarize violations = count() by device\n| extend description = \"Failed Module Starts\";\nlet diskSpace = getConsecutiveFailures(alerts)\n| where AlertDescription contains \"disk-space\"\n| summarize violations = count() by device\n| extend description = \"Disk Space\";\nlet mergeViolations = (T1:(device: string, description: string, violations: long), T2:(device: string, description: string, violations: long)) {\nT1\n  | join kind = leftouter (T2 | extend device = tolower(device)) on device, description\n  | project-away device1, description1\n  | extend violations = iff(isnull(violations1) == false, violations1, violations)\n  | project-away violations1\n  | extend violations = iff(device contains \"winpro\" and (description contains \"Memory\" or description contains \"Disk\" or description contains \"cpu\"), -1, violations)\n};\nlet tmp0 = mergeViolations(deviceDescriptions, numberOfMetrics);\nlet tmp1 = mergeViolations(tmp0, upstreamMessageRate);\nlet tmp2 = mergeViolations(tmp1, localMessageRate);\nlet tmp3 = mergeViolations(tmp2, reportedPropertyRate);\nlet tmp4 = mergeViolations(tmp3, queueLength);\nlet tmp5 = mergeViolations(tmp4, edgeAgentCPU);\nlet tmp6 = mergeViolations(tmp5, edgeHubCPU);\nlet tmp7 = mergeViolations(tmp6, edgeAgentMemory);\nlet tmp8 = mergeViolations(tmp7, edgeHubMemory);\nlet tmp9 = mergeViolations(tmp8, moduleStarts);\nlet tmp10 = mergeViolations(tmp9, diskSpace);\ntmp10\n| evaluate pivot(description, avg(violations))\n| project-reorder * asc\n",
      "resultFormat": "table",
      "workspace": "fdf47b96-87f3-4b86-90b9-d83e2deae8a0"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "5ed2dcb6-29bb-40de-a855-8c24a8260343"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 87 },
   "content": "-----------------------\n# Stress\n\n\n"
  },
  {
   "title": "Test Scenarios",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "let branchIdentifier = case(\"$BranchName\" == \"refs/heads/master\", \"master\", \"$BranchName\" == \"refs/heads/release/1.0.8\", \"1.0.8\", \"$BranchName\" == \"refs/heads/release/1.0.9\", \"1.0.9\", \"None\");\nlet stressIdentifier = \"Stress\";\nlet mostRecentBuildNumber = toscalar(messagingReportsLonghaulStress_CL\n| where testInfo_TestName_s == stressIdentifier and branchIdentifier == testInfo_BuildSourceBranch_s\n| summarize arg_max(TimeGenerated, testInfo_TestBuildNumber_s)\n| project testInfo_TestBuildNumber_s);\nlet twinsReport = twinReportsLonghaulStress_CL\n| where testInfo_TestBuildNumber_s == mostRecentBuildNumber and testInfo_TestName_s == stressIdentifier\n| extend Result = replace(\"True\", \"1\", tostring(isPassed_b))\n| extend Result = replace(\"False\", \"0\", tostring(Result)) \n| summarize arg_max(TimeGenerated, *) by testInfo_HostPlatform_s, moduleId_s\n| where testInfo_HostPlatform_s != \"\"\n| extend testInfo_HostPlatform_s = strcat(testInfo_HostPlatform_s, \" | \", testInfo_TestBuildNumber_s)\n| project testInfo_HostPlatform_s, moduleId_s, Result\n| evaluate pivot(moduleId_s, max(Result)); // have to use aggreation function max, but there will only ever be a max of 1 record \nlet messagingReport = messagingReportsLonghaulStress_CL\n| where testInfo_TestBuildNumber_s == mostRecentBuildNumber and testInfo_TestName_s == stressIdentifier\n| extend Result = replace(\"True\", \"1\", tostring(isPassed_b))\n| extend Result = replace(\"False\", \"0\", tostring(Result)) \n| summarize arg_max(TimeGenerated, *) by testInfo_HostPlatform_s, moduleId_s\n| where testInfo_HostPlatform_s != \"\"\n| extend testInfo_HostPlatform_s = strcat(testInfo_HostPlatform_s, \" | \", testInfo_TestBuildNumber_s)\n| project testInfo_HostPlatform_s, moduleId_s, Result\n| evaluate pivot(moduleId_s, max(Result)); // have to use aggreation function max, but there will only ever be a max of 1 record\ntwinsReport\n| join kind= leftouter (\n   messagingReport \n) on testInfo_HostPlatform_s\n| project-away testInfo_HostPlatform_s1\n| extend loadGen1 = columnifexists(\"loadGen1\", \"0\")\n| extend loadGen2 = columnifexists(\"loadGen2\", \"0\")\n| extend loadGen3 = columnifexists(\"loadGen3\", \"0\")\n| extend loadGen4 = columnifexists(\"loadGen4\", \"0\")\n| extend twinTester1 = columnifexists(\"twinTester1\", \"0\")\n| extend twinTester2 = columnifexists(\"twinTester2\", \"0\")\n| extend twinTester3 = columnifexists(\"twinTester3\", \"0\")\n| extend twinTester4 = columnifexists(\"twinTester4\", \"0\")\n| project-reorder testInfo_HostPlatform_s, loadGen1, loadGen2, loadGen3, loadGen4, twinTester1, twinTester2, twinTester3, twinTester4",
      "resultFormat": "table",
      "workspace": "fdf47b96-87f3-4b86-90b9-d83e2deae8a0"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "subscription": "5ed2dcb6-29bb-40de-a855-8c24a8260343"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 96 },
   "content": "-----------------------\n# Failing Builds / Tests\n\n\n"
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {
     "rawSql": "DECLARE @BuildStatus TABLE (SourceBranch VARCHAR(50), DefinitionName VARCHAR(50), Result VARCHAR(50), WebUri VARCHAR(200))\nINSERT INTO @BuildStatus\nSELECT VstsBuild.SourceBranch, VstsBuild.DefinitionName, Result, WebUri\nFROM \n  VstsBuild\n  INNER JOIN (SELECT VstsBuild.DefinitionName, SourceBranch, MAX(BuildNumber) AS MaxBuildNumber FROM VstsBuild GROUP BY VstsBuild.DefinitionName, SourceBranch) AS MostRecentBuildsPerDefinitionAndBranch\n    ON VstsBuild.DefinitionName = MostRecentBuildsPerDefinitionAndBranch.DefinitionName AND VstsBuild.SourceBranch = MostRecentBuildsPerDefinitionAndBranch.SourceBranch and VstsBuild.BuildNumber = MostRecentBuildsPerDefinitionAndBranch.MaxBuildNumber\n\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @BuildStatus SET Result = REPLACE(Result, 'Failed', '0')\n\n\nSELECT DefinitionName, WebUri\nFROM\n@BuildStatus\nWHERE SourceBranch = '$BranchName' AND Result != '1'"
    },
    {
     "rawSql": "DECLARE @ReleaseEnvironmentStatus TABLE (ReleaseId VARCHAR(50), Result VARCHAR(50))\n\nINSERT INTO @ReleaseEnvironmentStatus\nSELECT ReleaseId, Status FROM VstsReleaseEnvironment\n\nUPDATE @ReleaseEnvironmentStatus SET Result = REPLACE(Result, 'Succeeded', '1')\nUPDATE @ReleaseEnvironmentStatus SET Result = REPLACE(Result, 'Canceled', '0.5')\nUPDATE @ReleaseEnvironmentStatus SET Result = REPLACE(Result, 'NotStarted', '0.5')\nUPDATE @ReleaseEnvironmentStatus SET Result = REPLACE(Result, 'InProgress', '0.5')\nUPDATE @ReleaseEnvironmentStatus SET Result = REPLACE(Result, 'Failed', '0')\nUPDATE @ReleaseEnvironmentStatus SET Result = REPLACE(Result, 'Rejected', '0')\nUPDATE @ReleaseEnvironmentStatus SET Result = REPLACE(Result, 'PartiallySucceeded', '0')\n\nSELECT VstsRelease.DefinitionName, VstsRelease.WebUri FROM \n  VstsRelease\n  INNER JOIN (SELECT ReleaseId, MIN(Result) AS Result FROM @ReleaseEnvironmentStatus GROUP BY ReleaseId) AS ReleaseIdToAggregatedStatus ON VstsRelease.Id = ReleaseIdToAggregatedStatus.ReleaseId\n    INNER JOIN (SELECT VstsRelease.DefinitionName, SourceBranch, MAX(Id) AS MaxReleaseId FROM VstsRelease GROUP BY VstsRelease.DefinitionName, SourceBranch) AS MostRecentReleasesPerDefinitionAndBranch\n      ON VstsRelease.DefinitionName = MostRecentReleasesPerDefinitionAndBranch.DefinitionName AND VstsRelease.SourceBranch = MostRecentReleasesPerDefinitionAndBranch.SourceBranch AND VstsRelease.Id = MostRecentReleasesPerDefinitionAndBranch.MaxReleaseId\n      WHERE VstsRelease.SourceBranch = '$BranchName' AND ReleaseIdToAggregatedStatus.Result != '1'"
    }
   ]
  }
 ]
}