# Please refer to the issue-labeler documentation here: https://github.com/github/issue-labeler
name: Label all github issues
on:
  issues:
    types: opened

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@3ae0e4623c1fda729347ae0d8f1c2e52302ef4c6 # v2.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/ISSUE_TEMPLATE/issue-label-list.yml
        enable-versioned-regex: 0