# Please refer to the issue-labeler documentation here: https://github.com/github/issue-labeler
name: Label all github issues
on:
  issues:
    types: opened

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@ccca1e16fcb66762200e616fc29b57b940c1cb67 # v3.5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/ISSUE_TEMPLATE/issue-label-list.yml
        enable-versioned-regex: 0