name: Mark stale issues and pull requests
on:
  schedule:
  - cron: "0 0 * * *"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@0649bd81195b7ac109fbf9dde113af7e58a78b8e # v1.1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is being marked as stale because it has been open for 30 days with no activity.'
        stale-issue-label: 'no-issue-activity'
        days-before-stale: 30
        days-before-close: 99999
        exempt-issue-label: 'enhancement'
